"use strict";

window.creoleNameBases = [
  {name: "West African English Creole", i: 307, min: 4, max: 12, d: "lnrt", m: 0, b: "Freetown,Bo,Kenema,Koindu,Waterloo,Port Loko,Makeni,Koidu,Monrovia,Buchanan,Gbarnga,Harper,Robertsport,Paynesville,Clara Town,New Kru Town,Lagos,Port Harcourt,Warri,Benin City,Calabar,Accra,Tema,Sekondi,Takoradi,Koforidua,Tamale,Kumasi"},
  {name: "Caribbean English Creole", i: 308, min: 4, max: 12, d: "lnrt", m: 0, b: "Bridgetown,Speightstown,Holetown,Oistins,Castries,Soufriere,Vieux Fort,Kingstown,Georgetown,Barrouallie,Roseau,Portsmouth,St Johns,All Saints,Piggotts,The Valley,Charlestown,Philipsburg,Marigot,Basseterre,Charlestown Nevis,St Georges,Grenville,Scarborough,Port of Spain,San Fernando,Arima"},
  {name: "Pacific English Creole", i: 309, min: 4, max: 12, d: "lnrt", m: 0, b: "Port Vila,Luganville,Isangel,Sola,Lenakel,Honiara,Auki,Gizo,Noro,Tulaghi,Suva,Lautoka,Nadi,Labasa,Savusavu,Apia,Vaitele,Faleula,Pago Pago,Nuku'alofa,Neiafu,Funafuti,Vaitupu,Majuro,Kwajalein,Tarawa,Bairiki"},
  {name: "Malay-based Creole", i: 310, min: 4, max: 12, d: "lnrt", m: 0, b: "Malacca,George Town,Butterworth,Alor Setar,Ipoh,Johor Bahru,Pasir Gudang,Shah Alam,Petaling Jaya,Klang,Seremban,Melaka City,Kota Bharu,Kuala Terengganu,Kuantan,Kuching,Miri,Sibu,Kota Kinabalu,Sandakan,Tawau,Jakarta,Surabaya,Bandung,Semarang,Medan,Palembang"},
  {name: "Slavic", i: 5, min: 5, max: 12, d: "lnrt", m: 0, b: "Belgrade,Sofia,Zagreb,Sarajevo,Skopje,Podgorica,Ljubljana,Prague,Brno,Ostrava,Plzen,Warsaw,Krakow,Lodz,Wroclaw,Gdansk,Katowice,Opole,Bialystok,Lublin,Minsk,Gomel,Mogilev,Vitebsk,Polotsk,Brest,Grodno,Moscow,Saint Petersburg,Novgorod,Tver,Smolensk,Rostov,Kazan,Perm,Samara,Nizhny Novgorod,Kyiv,Kharkiv,Lviv,Odessa,Dnipro,Poltava,Sumy,Chernihiv,Banja Luka,Split,Varna,Burgas,Rijeka"},
  {name: "Yapese (dedicated)", i: 1550, min: 4, max: 11, d: "lnrt", m: 0, b: "Yap,Waqab,Waqaab,Wa'ab,Waab,Marbaaq,Marfach,Yap Proper,Gagil-Tamil,Maap,Rumung,Tagireeng,Mount Taabiywol,Dalipebinaw,Fanif,Gagil,Gilman,Kanifay,Rull,Tomil,Weloy,Colonia"},
  {name: "Maisin (dedicated)", i: 1551, min: 4, max: 11, d: "lnrt", m: 0, b: "Maisin,Collingwood Bay,Cape Nelson,Uwe,Popondetta,Kokoda,Tufi,Higaturu,Afore,Oro Bay,Safia,Ijivitari,Sohe,Kira,Tamata,Buna,Gona,Sanananda,Mount Lamington"},
  {name: "Norfuk (dedicated)", i: 1552, min: 4, max: 11, d: "lnrt", m: 0, b: "Norfuk,Norf'k,Norf'k Ailen,Norfolk Island,Kingston,Burnt Pine,Phillip Island,Nepean Island,Lord Howe Island,New Caledonia,A Trip Ina Stik"},
  {name: "Pitkern (dedicated)", i: 1553, min: 4, max: 11, d: "lnrt", m: 0, b: "Pitkern,Pitkern Ailen,Pitcairn Island,Pitcairn Islands,Adamstown,Bounty Bay,Pawala Valley Ridge,Henderson,Ducie,Oeno,Mangareva"}
];
