"use strict";
function editNamesbase() {
  if (customization) return;
  closeDialogs("#namesbaseEditor, .stable");
  $("#namesbaseEditor").dialog();

  if (modules.editNamesbase) return;
  modules.editNamesbase = true;

  // add listeners
  document.getElementById("namesbaseSelect").addEventListener("change", updateInputs);
  document.getElementById("namesbaseTextarea").addEventListener("change", updateNamesData);
  document.getElementById("namesbaseUpdateExamples").addEventListener("click", updateExamples);
  document.getElementById("namesbaseExamples").addEventListener("click", updateExamples);
  document.getElementById("namesbaseName").addEventListener("input", updateBaseName);
  document.getElementById("namesbaseMin").addEventListener("input", updateBaseMin);
  document.getElementById("namesbaseMax").addEventListener("input", updateBaseMax);
  document.getElementById("namesbaseDouble").addEventListener("input", updateBaseDublication);
  document.getElementById("namesbaseAdd").addEventListener("click", namesbaseAdd);
  document.getElementById("namesbaseAnalyze").addEventListener("click", analyzeNamesbase);
  document.getElementById("namesbaseDefault").addEventListener("click", namesbaseRestoreDefault);
  document.getElementById("namesbaseDownload").addEventListener("click", namesbaseDownload);

  const uploader = document.getElementById("namesbaseToLoad");
  document.getElementById("namesbaseUpload").addEventListener("click", () => {
    uploader.addEventListener("change", e => uploadFile(e.target, d => namesbaseUpload(d, true)), { once: true });
    uploader.click();
  });
  document.getElementById("namesbaseUploadExtend").addEventListener("click", () => {
    uploader.addEventListener("change", e => uploadFile(e.target, d => namesbaseUpload(d, false)), { once: true });
    uploader.click();
  });

  document.getElementById("namesbaseCA").addEventListener("click", () => {
    openURL("https://cartographyassets.com/asset-category/specific-assets/azgaars-generator/namebases/");
  });
  document.getElementById("namesbaseSpeak").addEventListener("click", () => speak(namesbaseExamples.textContent));

  // Language Mixer references
  const mixerCategorySelect = byId("namesbaseMixerCategory");
  const mixerFamilySelect = byId("namesbaseMixerFamily");
  const mixerTagFilterSelect = byId("namesbaseMixerTagFilter");
  const mixerLanguageSelect = byId("namesbaseMixerLanguage");
  const mixerAddButton = byId("namesbaseMixerAdd");
  const mixerEvenButton = byId("namesbaseMixerEven");
  const mixerAddRandomButton = byId("namesbaseMixerAddRandom");
  const mixerRandomizeAllButton = byId("namesbaseMixerRandomizeAll");
  const mixerSelectionBody = byId("namesbaseMixerSelection");
  const mixerCountInput = byId("namesbaseMixerCount");
  const mixerGenerateButton = byId("namesbaseMixerGenerate");
  const mixerGenerateLocalButton = byId("namesbaseMixerGenerateLocal");
  const mixerResultArea = byId("namesbaseMixerResult");
  const mixerInsertButton = byId("namesbaseMixerInsert");
  const mixerInsertMode = byId("namesbaseMixerInsertMode");
  const mixerStatus = byId("namesbaseMixerStatus");
  const mixerAiModelSelect = byId("namesbaseAiModel");
  const mixerAiTemperatureInput = byId("namesbaseAiTemperature");
  const mixerAiKeyInput = byId("namesbaseAiKey");
  const mixerAiKeyHelpButton = byId("namesbaseAiKeyHelp");
  const mixerAiWebAccessInput = byId("namesbaseAiWebAccess");

  const mixer = {
    catalog: null,
    languages: [],
    generating: false
  };

  function clamp(value, min, max) {
    const v = isNaN(value) ? min : value;
    return Math.min(max, Math.max(min, v));
  }

  function getRandomWeightNearOne() {
    const r = Math.random();
    let raw;

    if (r < 0.98) {
      const u = (Math.random() + Math.random() + Math.random()) / 3;
      raw = 1 + (u - 0.5) * 1.2;
    } else {
      const exp = Math.random() * 3;
      raw = Math.pow(10, exp);
    }

    const value = Math.round(raw * 100) / 100;
    return clamp(value, 0.01, 1000);
  }

  // Filter state: when false (default), the Select Base menu only shows
  // namebases that are referenced by a culture on the current map, or that
  // were generated by a per-map mixer (Culture / Race / Language). Clicking
  // the "Show all" button toggles this back to the legacy full list.
  let showAllNamebases = false;

  const showAllButton = document.getElementById("namesbaseShowAll");
  if (showAllButton) {
    showAllButton.addEventListener("click", () => {
      showAllNamebases = !showAllNamebases;
      showAllButton.classList.toggle("active", showAllNamebases);
      createBasesList();
    });
  }

  if (mixerLanguageSelect) initLanguageMixer();

  createBasesList();
  updateInputs();

  $("#namesbaseEditor").dialog({
    title: "Namesbase Editor",
    width: "60vw",
    position: { my: "center", at: "center", of: "svg" }
  });

  function getUsedNamebaseIndices() {
    // No pack yet (e.g. editor opened before map generation): treat all as unused.
    if (typeof pack === "undefined" || !pack || !Array.isArray(pack.cultures)) return new Set();

    const used = new Set();
    for (let i = 0; i < pack.cultures.length; i++) {
      const base = pack.cultures[i] && pack.cultures[i].base;
      if (typeof base === "number" && base >= 0) used.add(base);
    }
    return used;
  }

  function isMixerBase(base) {
    if (!base) return false;
    return Boolean(base.cultureMixer || base.raceMixerFor || base.languageMixer || base.isoWeights);
  }

  function shouldShowBase(i, usedSet, previousValue) {
    if (showAllNamebases) return true;
    const b = nameBases[i];
    if (!b) return false;
    if (isMixerBase(b)) return true;
    if (usedSet && usedSet.has(i)) return true;
    // Always keep the previously-selected base visible so toggling the
    // filter doesn't hide the entry the user is currently editing.
    if (previousValue !== undefined && +previousValue === i) return true;
    return false;
  }

  function createBasesList() {
    const select = document.getElementById("namesbaseSelect");
    const previousValue = select.value;
    const usedSet = getUsedNamebaseIndices();
    select.innerHTML = "";

    let inUse = 0;
    let mixed = 0;
    let other = 0;
    nameBases.forEach((b, i) => {
      if (!b) return;
      if (!shouldShowBase(i, usedSet, previousValue)) return;
      select.options.add(new Option(b.name, i));
      if (isMixerBase(b)) mixed++;
      else if (usedSet.has(i)) inUse++;
      else other++;
    });

    // Safety net: never leave the dropdown empty. This happens when a user
    // uploads a fresh namesbase file that no culture references yet.
    if (!select.options.length && nameBases.some(b => b)) {
      showAllNamebases = true;
      if (showAllButton) showAllButton.classList.add("active");
      nameBases.forEach((b, i) => {
        if (b) select.options.add(new Option(b.name, i));
      });
      other = nameBases.filter(b => b).length;
    }

    if (previousValue && select.querySelector(`option[value="${previousValue}"]`)) {
      select.value = previousValue;
    }

    // Surface a tooltip on the select with a quick count breakdown.
    const total = nameBases.filter(b => b).length;
    if (total) {
      const visible = inUse + mixed + other;
      select.title = `Showing ${visible} of ${total} namebases (in use: ${inUse}, mixed: ${mixed}, other: ${other})`;
    }
  }

  function updateInputs() {
    const base = +document.getElementById("namesbaseSelect").value;
    if (!nameBases[base]) return tip(`Namesbase ${base} is not defined`, false, "error");

    document.getElementById("namesbaseTextarea").value = nameBases[base].b;
    document.getElementById("namesbaseName").value = nameBases[base].name;
    document.getElementById("namesbaseMin").value = nameBases[base].min;
    document.getElementById("namesbaseMax").value = nameBases[base].max;
    document.getElementById("namesbaseDouble").value = nameBases[base].d;
    updateExamples();
  }

  function updateExamples() {
    const base = +document.getElementById("namesbaseSelect").value;
    let examples = "";
    for (let i = 0; i < 7; i++) {
      const example = Names.getBase(base);
      if (example === undefined) {
        examples = "Cannot generate examples. Please verify the data";
        break;
      }
      if (i) examples += ", ";
      examples += example;
    }
    document.getElementById("namesbaseExamples").innerHTML = examples;
  }

  function updateNamesData() {
    const base = +document.getElementById("namesbaseSelect").value;
    const input = document.getElementById("namesbaseTextarea");
    if (input.value.split(",").length < 3)
      return tip("The names data provided is too short of incorrect", false, "error");

    const securedNamesData = input.value.replace(/[/|]/g, "");
    nameBases[base].b = securedNamesData;
    input.value = securedNamesData;
    Names.updateChain(base);
  }

  function updateBaseName() {
    const base = +document.getElementById("namesbaseSelect").value;
    const select = document.getElementById("namesbaseSelect");

    const rawName = this.value;
    const name = rawName.replace(/[/|]/g, "");

    select.options[namesbaseSelect.selectedIndex].innerHTML = name;
    nameBases[base].name = name;
  }

  function updateBaseMin() {
    const base = +document.getElementById("namesbaseSelect").value;
    if (+this.value > nameBases[base].max) return tip("Minimal length cannot be greater than maximal", false, "error");
    nameBases[base].min = +this.value;
  }

  function updateBaseMax() {
    const base = +document.getElementById("namesbaseSelect").value;
    if (+this.value < nameBases[base].min) return tip("Maximal length should be greater than minimal", false, "error");
    nameBases[base].max = +this.value;
  }

  function updateBaseDublication() {
    const base = +document.getElementById("namesbaseSelect").value;
    nameBases[base].d = this.value;
  }

  function analyzeNamesbase() {
    const namesSourceString = document.getElementById("namesbaseTextarea").value;
    const namesArray = namesSourceString.toLowerCase().split(",");
    const length = namesArray.length;
    if (!namesSourceString || !length) return tip("Names data should not be empty", false, "error");

    const chain = Names.calculateChain(namesSourceString);
    const variety = rn(d3.mean(Object.values(chain).map(keyValue => keyValue.length)));

    const wordsLength = namesArray.map(n => n.length);

    const nonLatin = namesSourceString.match(/[^\u0000-\u007f]/g);
    const nonBasicLatinChars = nonLatin
      ? unique(
        namesSourceString
          .match(/[^\u0000-\u007f]/g)
          .join("")
          .toLowerCase()
      ).join("")
      : "none";

    const geminate = namesArray.map(name => name.match(/[^\w\s]|(.)(?=\1)/g) || []).flat();
    const doubled = unique(geminate).filter(
      char => geminate.filter(doudledChar => doudledChar === char).length > 3
    ) || ["none"];

    const duplicates = unique(namesArray.filter((e, i, a) => a.indexOf(e) !== i)).join(", ") || "none";
    const multiwordRate = d3.mean(namesArray.map(n => +n.includes(" ")));

    const getLengthQuality = () => {
      if (length < 30)
        return "<span data-tip='Namesbase contains < 30 names - not enough to generate reasonable data' style='color:red'>[not enough]</span>";
      if (length < 100)
        return "<span data-tip='Namesbase contains < 100 names - not enough to generate good names' style='color:darkred'>[low]</span>";
      if (length <= 400)
        return "<span data-tip='Namesbase contains a reasonable number of samples' style='color:green'>[good]</span>";
      return "<span data-tip='Namesbase contains > 400 names. That is too much, try to reduce it to ~300 names' style='color:darkred'>[overmuch]</span>";
    };

    const getVarietyLevel = () => {
      if (variety < 15)
        return "<span data-tip='Namesbase average variety < 15 - generated names will be too repetitive' style='color:red'>[low]</span>";
      if (variety < 30)
        return "<span data-tip='Namesbase average variety < 30 - names can be too repetitive' style='color:orange'>[mean]</span>";
      return "<span data-tip='Namesbase variety is good' style='color:green'>[good]</span>";
    };

    alertMessage.innerHTML = /* html */ `<div style="line-height: 1.6em; max-width: 20em">
      <div data-tip="Number of names provided">Namesbase length: ${length} ${getLengthQuality()}</div>
      <div data-tip="Average number of generation variants for each key in the chain">Namesbase variety: ${variety} ${getVarietyLevel()}</div>
      <hr />
      <div data-tip="The shortest name length">Min name length: ${d3.min(wordsLength)}</div>
      <div data-tip="The longest name length">Max name length: ${d3.max(wordsLength)}</div>
      <div data-tip="Average name length">Mean name length: ${rn(d3.mean(wordsLength), 1)}</div>
      <div data-tip="Common name length">Median name length: ${d3.median(wordsLength)}</div>
      <hr />
      <div data-tip="Characters outside of Basic Latin have bad font support">Non-basic chars: ${nonBasicLatinChars}</div>
      <div data-tip="Characters that are frequently (more than 3 times) doubled">Doubled chars: ${doubled.join(
      ""
    )}</div>
      <div data-tip="Names used more than one time">Duplicates: ${duplicates}</div>
      <div data-tip="Percentage of names containing space character">Multi-word names: ${rn(
      multiwordRate * 100,
      2
    )}%</div>
    </div>`;

    $("#alert").dialog({
      resizable: false,
      title: "Data Analysis",
      position: { my: "left top-30", at: "right+10 top", of: "#namesbaseEditor" },
      buttons: {
        OK: function () {
          $(this).dialog("close");
        }
      }
    });
  }

  function namesbaseAdd() {
    const base = nameBases.length;
    const b =
      "This,is,an,example,of,name,base,showing,correct,format,It,should,have,at,least,one,hundred,names,separated,with,comma";
    nameBases.push({ name: "Base" + base, min: 5, max: 12, d: "", m: 0, b });
    if (typeof window.refreshDefaultNameBaseIds === "function") window.refreshDefaultNameBaseIds();
    document.getElementById("namesbaseSelect").add(new Option("Base" + base, base));
    document.getElementById("namesbaseSelect").value = base;
    document.getElementById("namesbaseTextarea").value = b;
    document.getElementById("namesbaseName").value = "Base" + base;
    document.getElementById("namesbaseMin").value = 5;
    document.getElementById("namesbaseMax").value = 12;
    document.getElementById("namesbaseDouble").value = "";
    document.getElementById("namesbaseExamples").innerHTML = "Please provide names data";
  }

  function namesbaseRestoreDefault() {
    alertMessage.innerHTML = /* html */ `Are you sure you want to restore default namesbase?`;
    $("#alert").dialog({
      resizable: false,
      title: "Restore default data",
      buttons: {
        Restore: function () {
          $(this).dialog("close");
          Names.clearChains();
          nameBases = Names.getNameBases();
          createBasesList();
          updateInputs();
        },
        Cancel: function () {
          $(this).dialog("close");
        }
      }
    });
  }

  function namesbaseDownload() {
    const data = nameBases.map((b, i) => `${b.name}|${b.min}|${b.max}|${b.d}|${b.m}|${b.b}`).join("\r\n");
    const name = getFileName("Namesbase") + ".txt";
    downloadFile(data, name);
  }

  function namesbaseUpload(dataLoaded, override = true) {
    const data = dataLoaded.split("\r\n");
    if (!data || !data[0]) return tip("Cannot load a namesbase. Please check the data format", false, "error");

    Names.clearChains();
    if (override) nameBases = [];
    const unsafe = new RegExp(/[|/]/, "g");

    data.forEach(base => {
      const [rawName, min, max, d, m, rawNames] = base.split("|");
      const name = rawName.replace(unsafe, "");
      const names = rawNames.replace(unsafe, "");
      nameBases.push({ name, min: +min, max: +max, d, m: +m, b: names });
      if (typeof window.refreshDefaultNameBaseIds === "function") window.refreshDefaultNameBaseIds();
    });

    createBasesList();
    updateInputs();
  }

  function initLanguageMixer() {
    loadMixerCatalog().then(() => {
      renderMixerCategories();
      renderMixerFamilies();
      renderMixerLanguageOptions();
    });

    mixerCategorySelect?.addEventListener("change", () => {
      renderMixerFamilies();
      renderMixerLanguageOptions();
    });

    mixerFamilySelect?.addEventListener("change", () => {
      renderMixerLanguageOptions();
    });

    mixerTagFilterSelect?.addEventListener("change", () => {
      renderMixerLanguageOptions();
    });

    mixerAddButton?.addEventListener("click", e => {
      e.preventDefault();
      addLanguageToMix(mixerLanguageSelect.value);
    });

    mixerEvenButton?.addEventListener("click", e => {
      e.preventDefault();
      distributeMixerWeights();
    });

    mixerAddRandomButton?.addEventListener("click", e => {
      e.preventDefault();
      addRandomLanguageToMixFromFilters();
    });

    mixerRandomizeAllButton?.addEventListener("click", e => {
      e.preventDefault();
      randomizeAllMixerWeights();
    });

    mixerGenerateButton?.addEventListener("click", e => {
      e.preventDefault();
      generateMixerNames();
    });

    mixerGenerateLocalButton?.addEventListener("click", e => {
      e.preventDefault();
      generateMixerNamesLocal();
    });

    mixerInsertButton?.addEventListener("click", e => {
      e.preventDefault();
      insertMixerNamesIntoBase();
    });

    initMixerAiControls();
    renderMixerSelection();
  }

  async function addRandomLanguageToMixFromFilters() {
    await loadMixerCatalog();
    if (!mixer.catalog || !mixer.catalog.length) return;

    const selectedCategory = mixerCategorySelect?.value || "";
    const selectedFamily = mixerFamilySelect?.value || "";
    const selectedTagFilter = mixerTagFilterSelect?.value || "";

    let options = mixer.catalog;
    if (selectedCategory) options = options.filter(lang => lang.category === selectedCategory);
    if (selectedFamily) options = options.filter(lang => lang.family === selectedFamily);
    if (selectedTagFilter === "isolate") {
      options = options.filter(lang => lang.category === "Language isolate");
    } else if (selectedTagFilter === "unclassified") {
      options = options.filter(
        lang =>
          lang.category === "Unclassified" || (Array.isArray(lang.tags) && lang.tags.indexOf("unclassified") !== -1)
      );
    } else if (selectedTagFilter === "hypothetical") {
      options = options.filter(
        lang =>
          lang.category === "Hypothetical" || (Array.isArray(lang.tags) && lang.tags.indexOf("hypothetical") !== -1)
      );
    }

    const usedIsos = new Set(mixer.languages.map(l => l.iso));
    options = options.filter(lang => !(Array.isArray(lang.tags) && lang.tags.includes("family")) && !usedIsos.has(lang.iso));

    if (!options.length) {
      return tip("No more matching languages to add for the current filters", false, "warn");
    }

    const randomIndex = Math.floor(Math.random() * options.length);
    const iso = options[randomIndex].iso;
    addLanguageToMix(iso);
  }

  function initMixerAiControls() {
    if (!mixerAiModelSelect || !mixerAiTemperatureInput || !mixerAiKeyInput) return;

    function loadFromStorage() {
      mixerAiModelSelect.options.length = 0;
      if (typeof MODELS === "object" && MODELS) {
        Object.keys(MODELS).forEach(model => mixerAiModelSelect.options.add(new Option(model, model)));
      }

      let storedModel = localStorage.getItem("fmg-ai-model");
      if (!storedModel || (typeof MODELS === "object" && MODELS && !MODELS[storedModel])) {
        storedModel = typeof DEFAULT_MODEL !== "undefined" ? DEFAULT_MODEL : storedModel;
      }
      if (storedModel) mixerAiModelSelect.value = storedModel;

      let provider = null;
      if (storedModel && typeof MODELS === "object" && MODELS) {
        provider = MODELS[storedModel];
      }
      const key = provider ? localStorage.getItem(`fmg-ai-kl-${provider}`) || "" : "";
      mixerAiKeyInput.value = key;

      const temperature = localStorage.getItem("fmg-ai-temperature");
      mixerAiTemperatureInput.value = temperature !== null ? temperature : "1";

      const webAccess = typeof getStoredAiWebAccess === "function" ? getStoredAiWebAccess() : localStorage.getItem("fmg-ai-web-access") === "1";
      if (mixerAiWebAccessInput) mixerAiWebAccessInput.checked = webAccess;
    }

    function saveToStorage() {
      const model = mixerAiModelSelect.value;
      if (model && typeof MODELS === "object" && MODELS && MODELS[model]) {
        localStorage.setItem("fmg-ai-model", model);
        const provider = MODELS[model];
        localStorage.setItem(`fmg-ai-kl-${provider}`, mixerAiKeyInput.value || "");
      }

      const temperatureNumber = mixerAiTemperatureInput.valueAsNumber;
      if (!isNaN(temperatureNumber)) {
        localStorage.setItem("fmg-ai-temperature", temperatureNumber);
      }

      const webAccess = !!(mixerAiWebAccessInput && mixerAiWebAccessInput.checked);
      localStorage.setItem("fmg-ai-web-access", webAccess ? "1" : "0");
    }

    mixerAiModelSelect.addEventListener("change", saveToStorage);
    mixerAiTemperatureInput.addEventListener("change", saveToStorage);
    mixerAiKeyInput.addEventListener("change", saveToStorage);
    if (mixerAiWebAccessInput) mixerAiWebAccessInput.addEventListener("change", saveToStorage);

    if (mixerAiKeyHelpButton) {
      mixerAiKeyHelpButton.addEventListener("click", function () {
        const model = mixerAiModelSelect.value;
        if (!model || typeof MODELS !== "object" || !MODELS || !PROVIDERS) return;
        const provider = MODELS[model];
        if (!provider || !PROVIDERS[provider]) return;
        openURL(PROVIDERS[provider].keyLink);
      });
    }

    loadFromStorage();
  }

  async function loadMixerCatalog() {
    if (mixer.catalog) return mixer.catalog;
    if (window.languageMixerCatalog) {
      // Ensure the preloaded catalog is sorted the same way as fetched data
      mixer.catalog = window.languageMixerCatalog.sort((a, b) => (a.region + a.name).localeCompare(b.region + b.name));
      return mixer.catalog;
    }

    try {
      const res = await fetch(`./config/language-mixes.json?v=${VERSION}`);
      if (!res.ok) throw new Error(res.statusText);
      const data = await res.json();
      mixer.catalog = data.sort((a, b) => (a.region + a.name).localeCompare(b.region + b.name));
      window.languageMixerCatalog = mixer.catalog;
    } catch (error) {
      tip("Cannot load language catalog. Please reload the app.", false, "error");
      ERROR && console.error(error);
      mixer.catalog = [];
    }

    return mixer.catalog;
  }

  function renderMixerCategories() {
    if (!mixerCategorySelect || !mixer.catalog) return;
    const categories = Array.from(new Set(mixer.catalog.map(lang => lang.category).filter(Boolean))).sort((a, b) =>
      a.localeCompare(b)
    );
    mixerCategorySelect.innerHTML = "";
    const allOption = document.createElement("option");
    allOption.value = "";
    allOption.textContent = "All categories";
    mixerCategorySelect.append(allOption);
    categories.forEach(category => {
      const option = document.createElement("option");
      option.value = category;
      option.textContent = category;
      mixerCategorySelect.append(option);
    });
  }

  function renderMixerFamilies() {
    if (!mixerFamilySelect || !mixer.catalog) return;
    const selectedCategory = mixerCategorySelect?.value || "";
    let source = mixer.catalog;
    if (selectedCategory) source = source.filter(lang => lang.category === selectedCategory);
    const families = Array.from(
      new Set(
        source.map(lang => lang.family || lang.category).filter(Boolean)
      )
    ).sort((a, b) => a.localeCompare(b));
    const previousValue = mixerFamilySelect.value;
    mixerFamilySelect.innerHTML = "";
    const allOption = document.createElement("option");
    allOption.value = "";
    allOption.textContent = "All families";
    mixerFamilySelect.append(allOption);
    families.forEach(family => {
      const option = document.createElement("option");
      option.value = family;
      option.textContent = family;
      mixerFamilySelect.append(option);
    });
    if (previousValue && families.includes(previousValue)) {
      mixerFamilySelect.value = previousValue;
    }
  }

  function formatMixerTagBadge(meta, inline = false) {
    if (!meta || !meta.tags || !meta.tags.length) return "";
    const tags = [];
    if (meta.tags.includes("extinct")) tags.push("extinct");
    if (meta.tags.includes("pidgin")) tags.push("pidgin");
    if (meta.tags.includes("mixed")) tags.push("mixed");
    if (meta.tags.includes("creole")) tags.push("creole");
    if (meta.tags.includes("unclassified")) tags.push("unclassified");
    if (meta.tags.includes("hypothetical")) tags.push("hypothetical");
    if (meta.tags.includes("proto")) tags.push("proto");
    if (meta.tags.includes("family")) tags.push("family");
    if (!tags.length) return "";
    const label = `[${tags.join(", ")}]`;
    if (inline) return label;
    return `<span style="opacity:.7;font-size:.85em">${label}</span>`;
  }

  function formatMixerLabel(meta) {
    if (!meta) return "";
    const parts = [meta.name || meta.iso];
    if (meta.region) parts.push(`• ${meta.region}`);
    const badge = formatMixerTagBadge(meta, true);
    return badge ? `${parts.join(" ")} ${badge}` : parts.join(" ");
  }

  function renderMixerLanguageOptions() {
    if (!mixerLanguageSelect || !mixer.catalog) return;
    mixerLanguageSelect.innerHTML = "";
    const selectedCategory = mixerCategorySelect?.value || "";
    const selectedFamily = mixerFamilySelect?.value || "";
    const selectedTagFilter = mixerTagFilterSelect?.value || "";
    let options = mixer.catalog;
    if (selectedCategory) options = options.filter(lang => lang.category === selectedCategory);
    if (selectedFamily) options = options.filter(lang => lang.family === selectedFamily);
    if (selectedTagFilter === "isolate") {
      options = options.filter(lang => lang.category === "Language isolate");
    } else if (selectedTagFilter === "unclassified") {
      options = options.filter(
        lang =>
          lang.category === "Unclassified" || (Array.isArray(lang.tags) && lang.tags.indexOf("unclassified") !== -1)
      );
    } else if (selectedTagFilter === "hypothetical") {
      options = options.filter(
        lang =>
          lang.category === "Hypothetical" || (Array.isArray(lang.tags) && lang.tags.indexOf("hypothetical") !== -1)
      );
    }
    options.forEach(lang => {
      if (lang.tags && lang.tags.includes("family")) return; // skip family-only pseudo-languages
      const option = document.createElement("option");
      option.value = lang.iso;
      option.textContent = formatMixerLabel(lang);
      mixerLanguageSelect.append(option);
    });
  }

  function addLanguageToMix(iso) {
    if (!iso) return;
    if (mixer.languages.some(lang => lang.iso === iso)) {
      return tip("Language already added to the mix", false, "warn");
    }
    mixer.languages.push({ iso, weight: 1 });
    renderMixerSelection();
  }

  function renderMixerSelection() {
    if (!mixerSelectionBody) return;
    mixerSelectionBody.innerHTML = "";

    if (!mixer.languages.length) {
      mixerSelectionBody.innerHTML =
        '<tr><td colspan="4" style="text-align:center; padding: .4em">Add languages to start mixing</td></tr>';
      return;
    }

    mixer.languages.forEach(lang => {
      const meta = getMixerMeta(lang.iso);
      const row = document.createElement("tr");
      row.dataset.iso = lang.iso;
      row.innerHTML = `
        <td>
          <div>${meta?.name || lang.iso} ${formatMixerTagBadge(meta)}</div>
          <small>${[meta?.category, meta?.subgroup].filter(Boolean).join(" • ")}</small>
        </td>
        <td>${meta?.region || ""}</td>
        <td>
          <input type="number" min="0.01" max="1000" step="0.01" value="${lang.weight.toFixed(2)}" class="namesbaseMixerWeight" style="width:5em" />
        </td>
        <td>
          <button class="icon-shuffle namesbaseMixerRandomizeWeight" data-iso="${lang.iso}" data-tip="Randomize weight"></button>
          <button class="icon-trash-empty namesbaseMixerRemove" data-iso="${lang.iso}" data-tip="Remove language"></button>
        </td>
      `;
      mixerSelectionBody.append(row);
    });

    mixerSelectionBody.querySelectorAll(".namesbaseMixerWeight").forEach(input => {
      input.addEventListener("input", function () {
        const iso = this.closest("tr").dataset.iso;
        const lang = mixer.languages.find(l => l.iso === iso);
        let value = parseFloat(this.value);
        if (isNaN(value)) value = 1;
        if (value <= 0) value = 0.01;
        if (value > 1000) value = 1000;
        value = Math.round(value * 100) / 100;
        lang.weight = value;
        this.value = value.toFixed(2);
      });
    });

    mixerSelectionBody.querySelectorAll(".namesbaseMixerRemove").forEach(button => {
      button.addEventListener("click", () => {
        mixer.languages = mixer.languages.filter(l => l.iso !== button.dataset.iso);
        renderMixerSelection();
      });
    });

    mixerSelectionBody.querySelectorAll(".namesbaseMixerRandomizeWeight").forEach(button => {
      button.addEventListener("click", () => {
        const iso = button.closest("tr").dataset.iso;
        const lang = mixer.languages.find(l => l.iso === iso);
        if (!lang) return;
        const newWeight = getRandomWeightNearOne();
        lang.weight = newWeight;
        const input = button.closest("tr").querySelector(".namesbaseMixerWeight");
        if (input) input.value = newWeight.toFixed(2);
      });
    });
  }

  function distributeMixerWeights() {
    if (!mixer.languages.length) {
      return tip("Add languages before distributing weights", false, "warn");
    }
    mixer.languages.forEach(lang => (lang.weight = 1));
    renderMixerSelection();
  }

  function randomizeAllMixerWeights() {
    if (!mixer.languages.length) {
      return tip("Add languages before randomizing weights", false, "warn");
    }
    mixer.languages.forEach(lang => {
      lang.weight = getRandomWeightNearOne();
    });
    renderMixerSelection();
  }

  function getMixerMeta(iso) {
    return mixer.catalog?.find(lang => lang.iso === iso);
  }

  function generateMixerLanguageName() {
    if (!mixer.languages.length) return "";

    const samples = mixer.languages
      .map(lang => {
        const meta = getMixerMeta(lang.iso);
        return (meta && meta.name) || lang.iso || "";
      })
      .map(n => String(n).trim())
      .filter(Boolean);

    if (!samples.length) return "";

    // If there is only one sample, just reuse it
    if (samples.length === 1) return samples[0];

    const text = samples.join(",");
    let chain;
    try {
      chain = Names.calculateChain(text);
    } catch (error) {
      ERROR && console.error("Failed to calculate mixer language name chain", error);
      return "";
    }

    if (!chain || chain[""] === undefined) return "";

    const min = 4;
    const max = 14;

    function pickRandom(list) {
      if (!Array.isArray(list) || !list.length) return "";
      return list[Math.floor(Math.random() * list.length)] || "";
    }

    let v = chain[""];
    let cur = pickRandom(v);
    let w = "";

    for (let i = 0; i < 30; i++) {
      if (cur === "") {
        if (w.length < min) {
          cur = "";
          w = "";
          v = chain[""];
        } else break;
      } else {
        if (w.length + cur.length > max) {
          if (w.length < min) w += cur;
          break;
        } else {
          const lastChar = cur.charAt(cur.length - 1) || "";
          v = chain[lastChar] || chain[""];
        }
      }

      w += cur;
      cur = pickRandom(v);
    }

    let name = w.trim();
    if (!name || name.length < 3) return "";

    // Normalize casing: title-case, keep internal spaces/hyphens
    name = name
      .split(/([\s-]+)/)
      .map((part, idx) => {
        if (/^[\s-]+$/.test(part)) return part;
        if (!part) return part;
        const lower = part.toLowerCase();
        return lower.charAt(0).toUpperCase() + lower.slice(1);
      })
      .join("");

    return name;
  }

  async function generateMixerNames() {
    if (mixer.generating) return;
    await loadMixerCatalog();

    if (!mixer.languages.length) return tip("Please add at least one language", false, "error");

    const key = getStoredAiKey();
    if (!key) return tip("Please enter an AI API key in the AI Generator dialog first", false, "error");

    const model = getStoredAiModel();
    const provider = getAiProviderForModel(model);
    if (!provider || !PROVIDERS[provider]) return tip("Selected AI model is not supported", false, "error");

    const totalWeight = mixer.languages.reduce((sum, lang) => sum + lang.weight, 0);
    if (!totalWeight) return tip("Weights must be greater than zero", false, "error");

    const count = clamp(+mixerCountInput.value || 40, 5, 200);
    mixerCountInput.value = count;

    const breakdown = mixer.languages
      .map(lang => {
        const meta = getMixerMeta(lang.iso);
        const pct = Math.round((lang.weight / totalWeight) * 100);
        const lexifier = meta?.lexifier ? `, lexifier ${meta.lexifier}` : "";
        return `${meta?.name || lang.iso} (${pct}% mix, region ${meta?.region || "N/A"}, category ${meta?.category || "N/A"
          }${lexifier})`;
      })
      .join("; ");

    const prompt = `
Generate ${count} unique fantasy place names. Names must feel like a blend of these language families with the given weights: ${breakdown}.

Some sources are creoles, mixed languages, proto or hypothetical reconstructions, or family-level groupings, and may show tags such as [creole], [mixed], [proto], [hypothetical], [family] and an optional lexifier field. Interpret them as follows:
- Lexifier: If a source lists a lexifier (for example "lexifier English" or "lexifier Quechua–Spanish"), bias surface phonology and vocabulary toward those lexifier languages, with other sources influencing structure and secondary flavor.
- Creole / pidgin: Sources tagged as creole or pidgin should still sound strongly like their lexifier language(s), with only subtle substrate influence rather than a generic global mix.
- Mixed: Sources tagged as mixed already blend multiple lineages; keep that blended character but still respect the given region, family and lexifier information.
- Proto / hypothetical: Sources tagged as proto or hypothetical represent reconstructed or proposed stages; use them to shape patterns and phonotactics, but do not output obviously real-world historical names.
- Family: Sources tagged as family (for example "Romance", "Uralic" or "English-based Caribbean creoles family") represent broad family style rather than a single language; treat them as high-level stylistic umbrellas informed by their typical member languages.

Before you generate anything, infer for each source language its typical phonology, prosody, morphology type, and place-name patterns using its name, family, region, tags and any tools or web access you have. Do this analysis internally; do not output it directly.

When blending, mix the underlying linguistic features of the source languages, not just their spelling. Explicitly consider:
- Phonology and phonotactics: typical vowels, consonants, nasals, clusters, syllable shapes, stress patterns, and any vowel/consonant harmony.
- Prosodic "slantings": preferred syllable openings and closings, and the typical onset/coda clusters each language family favors.
- Morphology and word structure: isolating vs agglutinative vs fusional vs polysynthetic tendencies, common affixes or compounding patterns, and typical place-name morphemes.
- Syntax and grammar "feel": how multi-word names are ordered (e.g. modifiers vs heads, honorifics, and formals) so the overall structure matches the families and regions.
- Lexicon and semantics: roots and morphemes that feel typical for place names in those language families and regions, without copying real-world toponyms.

Guidelines:
- Return a comma-separated list only, no numbering or extra prose.
- Names should be 1-3 words, title case, 3-16 characters per word.
- Avoid diacritics that are not ASCII.
- Avoid adding generic global English or Latinate flavor unless those languages are explicitly part of the mix.
- Do not repeat names, and keep them pronounceable.
- Do not output any explanations or metadata, only the names.
    `.trim();

    const temperature = +localStorage.getItem("fmg-ai-temperature") || 0.9;
    const webAccess = typeof getStoredAiWebAccess === "function" ? getStoredAiWebAccess() : localStorage.getItem("fmg-ai-web-access") === "1";
    mixer.generating = true;
    mixerGenerateButton.disabled = true;
    setMixerStatus("Generating names...", "info");
    mixerResultArea.value = "";

    try {
      await requestAiCompletion({
        model,
        key,
        prompt,
        temperature,
        webAccess,
        onContent: content => {
          mixerResultArea.value += content;
        }
      });
      setMixerStatus("Generation completed. Review the names and insert when ready.", "success");
    } catch (error) {
      setMixerStatus(error.message || "Failed to generate names", "error");
      tip(error.message, true, "error", 4000);
    } finally {
      mixer.generating = false;
      mixerGenerateButton.disabled = false;
    }
  }

  function generateMixerNamesLocal() {
    if (!mixer.languages.length) return tip("Please add at least one language", false, "error");

    const isoWeights = mixer.languages.reduce((acc, lang) => {
      if (lang.weight > 0) acc[lang.iso] = lang.weight;
      return acc;
    }, {});

    if (!Object.keys(isoWeights).length) {
      return tip("Weights must be greater than zero", false, "error");
    }

    const count = clamp(+mixerCountInput.value || 40, 5, 200);
    mixerCountInput.value = count;

    if (!Names.getMixedByIso) {
      setMixerStatus("Local Markov mixer not loaded. Please refresh the page.", "error");
      return;
    }

    try {
      const names = Names.getMixedByIso(isoWeights, { count });
      if (!names || !names.length) {
        setMixerStatus("No names generated. Check language mapping.", "error");
        return;
      }

      mixerResultArea.value = names.join(", ");
      setMixerStatus(`Generated ${names.length} mixed names locally.`, "success");
    } catch (error) {
      setMixerStatus(error.message || "Failed to generate local names", "error");
      ERROR && console.error("Local mixer error:", error);
    }
  }

  function insertMixerNamesIntoBase() {
    const text = mixerResultArea.value;
    const names = parseMixerNames(text);
    if (!names.length) return tip("No generated names to insert", false, "warn");

    const textarea = document.getElementById("namesbaseTextarea");
    const mode = mixerInsertMode.value;

    const uniqueNewNames = Array.from(new Set(names)).filter(Boolean);

    if (mode === "new") {
      if (!uniqueNewNames.length) return tip("No generated names to insert", false, "warn");

      const base = nameBases.length;
      const selectedIndex = +document.getElementById("namesbaseSelect").value || 0;
      const sourceBase = nameBases[selectedIndex];

      const fallbackName = sourceBase && sourceBase.name ? `${sourceBase.name} mix` : "Base" + base;
      const generatedName = generateMixerLanguageName();
      const baseName = generatedName || fallbackName;
      const min = sourceBase && typeof sourceBase.min === "number" ? sourceBase.min : 5;
      const max = sourceBase && typeof sourceBase.max === "number" ? sourceBase.max : 12;
      const d = sourceBase && typeof sourceBase.d === "string" ? sourceBase.d : "";
      const m = sourceBase && typeof sourceBase.m === "number" ? sourceBase.m : 0;
      const b = uniqueNewNames.join(", ");

      nameBases.push({ name: baseName, min, max, d, m, b, languageMixer: true });
      if (typeof window.refreshDefaultNameBaseIds === "function") window.refreshDefaultNameBaseIds();

      createBasesList();
      const select = document.getElementById("namesbaseSelect");
      select.value = base;
      updateInputs();

      setMixerStatus(`${names.length} names added as a new language.`, "success");
      return;
    }

    const existing = textarea.value
      ? textarea.value
        .split(",")
        .map(n => n.trim())
        .filter(Boolean)
      : [];

    const combined = mode === "replace" ? names : [...existing, ...names];
    const uniqueNames = Array.from(new Set(combined)).filter(Boolean);
    textarea.value = uniqueNames.join(", ");

    updateNamesData();
    updateExamples();
    setMixerStatus(`${names.length} names ${mode === "replace" ? "replaced" : "appended"} to the base.`, "success");
  }

  function parseMixerNames(text) {
    return text
      .split(/\r?\n|,/)
      .map(n => n.trim())
      .map(n => n.replace(/^[\d\.\-\)\(]+/, ""))
      .filter(n => n.length > 1);
  }

  function setMixerStatus(message, type = "info") {
    if (!mixerStatus) return;
    const colors = { info: "", success: "green", error: "crimson", warn: "orange" };
    mixerStatus.style.color = colors[type] || "";
    mixerStatus.textContent = message;
  }
}
