"use strict";

window.oceaniaNameBases = [
  {
    "name": "Hawaiian",
    "i": 24,
    "min": 5,
    "max": 10,
    "d": "auo",
    "m": 1,
    "b": "Aapueo,Ahoa,Ahuakaio,Ahupau,Alaakua,Alae,Alaeloa,Alamihi,Aleamai,Alena,Alio,Aupokopoko,Halakaa,Haleu,Haliimaile,Hamoa,Hanakaoo,Hanaulu,Hanawana,Hanehoi,Haou,Hikiaupea,Hokuula,Honohina,Honokahua,Honokeana,Honokohau,Honolulu,Honomaele,Hononana,Honopou,Hoolawa,Huelo,Kaalaea,Kaapahu,Kaeo,Kahalehili,Kahana,Kahuai,Kailua,Kainehe,Kakalahale,Kakanoni,Kalenanui,Kaleoaihe,Kalialinui,Kalihi,Kalimaohe,Kaloi,Kamani,Kamehame,Kanahena,Kaniaula,Kaonoulu,Kapaloa,Kapohue,Kapuaikini,Kapunakea,Kauau,Kaulalo,Kaulanamoa,Kauluohana,Kaumakani,Kaumanu,Kaunauhane,Kaupakulua,Kawaloa,Keaa,Keaaula,Keahua,Keahuapono,Kealahou,Keanae,Keauhou,Kelawea,Keokea,Keopuka,Kikoo,Kipapa,Koakupuna,Koali,Kolokolo,Kopili,Kou,Kualapa,Kuhiwa,Kuholilea,Kuhua,Kuia,Kuikui,Kukoae,Kukohia,Kukuiaeo,Kukuipuka,Kukuiula,Kulahuhu,Lapakea,Lapueo,Launiupoko,Lole,Maalo,Mahinahina,Mailepai,Makaakini,Makaalae,Makaehu,Makaiwa,Makaliua,Makapipi,Makapuu,Maluaka,Manawainui,Mehamenui,Moalii,Moanui,Mohopili,Mokae,Mokuia,Mokupapa,Mooiki,Mooloa,Moomuku,Muolea,Nakaaha,Nakalepo,Nakaohu,Nakapehu,Nakula,Napili,Niniau,Nuu,Oloewa,Olowalu,Omaopio,Onau,Onouli,Opaeula,Opana,Opikoula,Paakea,Paeahu,Paehala,Paeohi,Pahoa,Paia,Pakakia,Palauea,Palemo,Paniau,Papaaea,Papaanui,Papaauhau,Papaka,Papauluana,Pauku,Paunau,Pauwalu,Pauwela,Pohakanele,Polaiki,Polanui,Polapola,Poopoo,Poponui,Poupouwela,Puahoowali,Puakea,Puako,Pualaea,Puehuehu,Pueokauiki,Pukaauhuhu,Pukuilua,Pulehu,Puolua,Puou,Puuhaehae,Puuiki,Puuki,Puulani,Puunau,Puuomaile,Uaoa,Uhao,Ukumehame,Ulaino,Ulumalu,Wahikuli,Waianae,Waianu,Waiawa,Waiehu,Waieli,Waikapu,Wailamoa,Wailaulau,Wainee,Waiohole,Waiohonu,Waiohuli,Waiokama,Waiokila,Waiopai,Waiopua,Waipao,Waipionui,Waipouli,Hilo,Kaneohe,Waipahu,Pearl City,Kahului,Lihue,Kihei,Wailuku"},
  {
    "name": "Australian Aboriginal",
    "i": 33,
    "min": 4,
    "max": 11,
    "d": "pam-AU",
    "m": 0,
    "b": "Maningrida,Yirrkala,Galiwinku,Gunbalanya,Nhulunbuy,Borroloola,Yuendumu,Papunya,Jabiru,Kununurra,Yulara,Wadeye,Katherine,Tennant Creek,Broome,Port Augusta,Wagga Wagga,Dubbo,Townsville,Cairns,Mackay,Rockhampton,Toowoomba,Gold Coast,Sunshine Coast,Newcastle,Geelong,Ballarat,Bendigo,Launceston,Canberra,Sydney,Melbourne,Brisbane,Perth,Adelaide,Darwin,Hobart,Alice Springs"},
  {
    "name": "Papuan",
    "i": 45,
    "min": 4,
    "max": 12,
    "d": "nic-GH",
    "m": 0,
    "b": "Tari,Mendi,Wabag,Ialibu,Koroba,Kagua,Kundiawa,Kerowagi,Minj,Banz,Goroka,Kainantu,Henganofi,Chuave,Obura,Wapenamanda,Kompiam,Porgera,Enga,Okapa,Menyamya,Finschhafen,Kikori,Tapu,Madang,Mount Hagen,Rabaul,Lae,Kokoda,Kerema,Kavieng,Arawa,Buka,Popondetta,Daru,Kiunga,Vanimo,Wewak,Lorengau,Mendi"},
  {
    "name": "Engan Papuan",
    "i": 50,
    "min": 4,
    "max": 12,
    "d": "nic-GH",
    "m": 0,
    "b": "Wabag,Wapenamanda,Kandep,Laiagam,Kompiam,Porgera,Ambum,Lagaip,Wapi,Yengis,Maip,Muritaka,Pilikambi,Paela,Hewa,Tsak,Maramuni,Enga,Lai"},
  {
    "name": "New Caledonia",
    "i": 56,
    "min": 4,
    "max": 12,
    "d": "nic-GH",
    "m": 0,
    "b": "Noumea,Dumbea,Paita,Mont-Dore,Boulouparis,La Foa,Bourail,Kone,Koumac,Poindimie,Hienghene,Thio,Houailou,Pouebo,Poum,Lifou,We,Mare,Tadine,Ouvea,Fayaoue,Canala,Yate,Voh,Kaala-Gomen,Pouembout,Sarramea,Farino,Moindou,Ouegoa"},
  {
    "name": "Nauruan",
    "i": 80,
    "min": 4,
    "max": 11,
    "d": "nic-GH",
    "m": 0,
    "b": "Yaren,Denigomodu,Aiwo,Anetan,Anabar,Anibare,Baitsi,Boe,Buada,Ewa,Ijuw,Meneng,Nibok,Uaboe,Anibare Bay,Buada Lagoon"},
  {
    "name": "Tok Pisin",
    "i": 81,
    "min": 4,
    "max": 11,
    "d": "nic-GH",
    "m": 0,
    "b": "Port Moresby,Lae,Madang,Wewak,Goroka,Kokopo,Popondetta,Kimbe,Daru,Alotau,Vanimo,Kundiawa,Kavieng,Buka,Lorengau,Kerema,Aitape,Wabag,Kieta,Mendi,Tari,Buin,Kiunga,Tufi,Kikori,Ihu,Balimo,Ambunti,Mount Hagen,Arawa,Rabaul"},
  {
    "name": "Ari (Papuan)",
    "i": 187,
    "min": 4,
    "max": 11,
    "d": "nic-GH",
    "m": 0,
    "b": "Western Province,Daru,Kiunga,Fly River,Ok Tedi,Tabubil,Balimo,Bamu River,Lake Murray,Nomad District,Mabudauan,Kundiawa,Port Moresby,Nomad,Wipim,Ningerum,Olsobip,Telefomin,Oksapmin,Tekin"},
  {
    "name": "Palaung",
    "i": 194,
    "min": 4,
    "max": 11,
    "d": "nic-GH",
    "m": 0,
    "b": "Namhsan,Mantong,Kyaukme,Hsipaw,Lashio,Muse,Laukkaing,Taunggyi,Kengtung,Mongmit,Kunlong,Hsenwi,Mongmao"},
  {
    "name": "Italo-Australian",
    "i": 452,
    "min": 4,
    "max": 11,
    "d": "ro-AU",
    "m": 0,
    "b": "Melbourne,Sydney,Perth,Adelaide,Brisbane,Canberra,Hobart,Geelong,Wollongong,Ballarat,Newcastle,Fremantle"},
  {
    "name": "Western Erzya",
    "i": 552,
    "min": 4,
    "max": 11,
    "d": "urj-RU",
    "m": 0,
    "b": "Ruzaevka,Insar,Kadoshkino,Kovylkino"},
  {
    "name": "Western Mansi",
    "i": 561,
    "min": 4,
    "max": 11,
    "d": "urj-RU",
    "m": 0,
    "b": "Kondo-Vozhe,Shaitanka,Pelim,Lozva,Sosva,Ivdel,Gari,Verkhoturye,Tavda,Turinsk"},
  {
    "name": "Transylvanian Plain",
    "i": 564,
    "min": 4,
    "max": 11,
    "d": "ro-RO",
    "m": 0,
    "b": "Cluj-Napoca,Turda,CÃ¢mpia Turzii,LuduÈ™,Gherla,Dej,Beclean,Reghin,TÃ¢rgu MureÈ™"},
  {
    "name": "Western Lombard",
    "i": 576,
    "min": 4,
    "max": 11,
    "d": "ro-IT",
    "m": 0,
    "b": "Milan,Monza,Busto Arsizio,Legnano,Rho,Saronno,Magenta,Abbiategrasso"},
  {
    "name": "Transylvanian",
    "i": 649,
    "min": 4,
    "max": 11,
    "d": "ro-RO",
    "m": 0,
    "b": "Cluj-Napoca,Brasov,Sibiu,Targu Mures,Alba Iulia,Bistrita,Deva,Zalau,Turda,Medias,Hunedoara,Sebes"},
  {
    "name": "West Walloon ",
    "i": 664,
    "min": 4,
    "max": 11,
    "d": "ro-FR",
    "m": 0,
    "b": "Charleroi,Thuin,Beaumont,Chimay,Walcourt,Gerpinnes,Fleurus,Gosselies,Jumet,Marchienne-au-Pont,Mont-sur-Marchienne,Marcinelle"},
  {
    "name": "Viti ",
    "i": 721,
    "min": 4,
    "max": 11,
    "d": "nic-GH",
    "m": 0,
    "b": "Michika,Madagali,Bazza,Vi,Gulak,Shuwa,Mubi,Hong,Gombi,Little Gombi,Song,Girei"},
  {
    "name": "Western Aragonese ",
    "i": 733,
    "min": 4,
    "max": 11,
    "d": "an-ES",
    "m": 0,
    "b": "Hecho,AnsÃ³,EmbÃºn,UrduÃ©s,Fago,AragÃ¼Ã©s,Jasa,AÃ­sa,Borau,AratorÃ©s,Castiello,VillanÃºa"},
  {
    "name": "Western Sicilian ",
    "i": 735,
    "min": 4,
    "max": 11,
    "d": "it-IT",
    "m": 0,
    "b": "Palermo,Trapani,Marsala,Mazara del Vallo,Alcamo,Castelvetrano,Erice,Castellammare del Golfo,Partinico,Carini,Monreale,Bagheria"},
  {
    "name": "Western Khanty ",
    "i": 761,
    "min": 4,
    "max": 11,
    "d": "nic-GH",
    "m": 0,
    "b": "Khanty-Mansiysk,Surgut,Nizhnevartovsk,Nefteyugansk,Nyagan,Kogalym,Langepas,Megion,Raduzhny,Pokachi,Uray,Lyantor"},
  {
    "name": "Western Neo-Aramaic ",
    "i": 818,
    "min": 4,
    "max": 11,
    "d": "nic-GH",
    "m": 0,
    "b": "Maaloula,Jubb'adin,Bakh'a,Saidnaya,Rankous,Yabroud,Nabk,Deir Atiyah,Qalamoun,Damascus,Homs,Hama"},
  {
    "name": "Central Transdanubian ",
    "i": 1068,
    "min": 4,
    "max": 11,
    "d": "nic-GH",
    "m": 0,
    "b": "SzÃ©kesfehÃ©rvÃ¡r,TatabÃ¡nya,GyÅ‘r,MosonmagyarÃ³vÃ¡r,KomÃ¡rom,Esztergom,Dorog,BÃ¡bolna,OroszlÃ¡ny,MÃ³richida"},
  {
    "name": "Guambiano ",
    "i": 1317,
    "min": 4,
    "max": 11,
    "d": "nic-GH",
    "m": 0,
    "b": "Guambiano,PopayÃ¡n,Silvia,PiendamÃ³,TotorÃ³,Mojarras,InzÃ¡,El Tambo,JambalÃ³,PuracÃ©,Cauca,Colombia"},
  {
    "name": "Western Himalayas ",
    "i": 1559,
    "min": 4,
    "max": 11,
    "d": "nic-GH",
    "m": 0,
    "b": "Western Himalayas,Kashmir,Ladakh,Jammu,Himachal Pradesh,Uttarakhand,India,Nepal Border,Tibet Border"},
  {
    "name": "West Himalayish ",
    "i": 1560,
    "min": 4,
    "max": 11,
    "d": "nic-GH",
    "m": 0,
    "b": "West Himalayish,Kullu,Manali,Shimla,Dharamsala,India,Himachal Pradesh,Himalayas,Tibet Border"},
  {
    "name": "Fijian ",
    "i": 1843,
    "min": 4,
    "max": 11,
    "d": "nic-GH",
    "m": 0,
    "b": "Suva,Lautoka,Nadi,Ba,Rakiraki,Labasa,Savusavu,Fiji,Oceania,South Pacific"},
  {
    "name": "Hawaiian ",
    "i": 1936,
    "min": 4,
    "max": 11,
    "d": "nic-GH",
    "m": 0,
    "b": "Hawaiian,Honolulu,Laie,Kaneohe,Maui,Molokai,Kauai,USA,Pacific Ocean,Islands"},
  {
    "name": "West Chadic family ",
    "i": 2013,
    "min": 4,
    "max": 11,
    "d": "nic-GH",
    "m": 0,
    "b": "Kano,Katsina,Zaria,Bauchi,Gombe,Potiskum,Nguru,Maradi,Zinder,Diffa"},
  {
    "name": "Kanak ",
    "i": 2099,
    "min": 4,
    "max": 11,
    "d": "nic-GH",
    "m": 0,
    "b": "Noumea,Kone,Koumac,Poindimie,Bourail,Canala,Hienghene,Lifou,Mare,Ouvea"},
  {
    "name": "Western Oceanic ",
    "i": 2126,
    "min": 4,
    "max": 11,
    "d": "nic-GH",
    "m": 0,
    "b": "Rabaul,Madang,Lae,Kimbe,Kavieng,Lorengau,Alotau,Popondetta,Vanimo,Daru,Kerema,Kundiawa"},
  {
    "name": "Kiribati ",
    "i": 2236,
    "min": 4,
    "max": 11,
    "d": "nic-GH",
    "m": 0,
    "b": "Tarawa,Butaritari,Makin,Abaiang,Marakei,Maiana,Abemama,Kuria,Aranuka,Nonouti,Tabiteuea,Beru"},
  {
    "name": "Kosraean ",
    "i": 2271,
    "min": 4,
    "max": 11,
    "d": "nic-GH",
    "m": 0,
    "b": "Lelu,Malem,Utwe,Tafunsak,Walung,Pilyuul,Sansrik,Tofol,Mutunnenea,Innem,Yela,Okat"},
  {
    "name": "Light Warlpiri ",
    "i": 2424,
    "min": 4,
    "max": 11,
    "d": "nic-GH",
    "m": 0,
    "b": "Alice Springs,Yuendumu,Lajamanu,Harts Range,Alice,Ayawarri"},
  {
    "name": "West Himalayish",
    "i": 2445,
    "min": 4,
    "max": 12,
    "d": "lnrt",
    "m": 0,
    "b": "Shimla,Solan,Kasauli,Dharampur,Parwanoo,Kandaghat,Nahan,Paonta Sahib,Chamba,Dalhousie,Kangra,Dharamshala,Palampur,Jogindernagar,Kullu,Manali,Mandi,Sundernagar,Bilaspur,Hamirpur,Una,Rampur,Baijnath,Keylong,Reckong Peo,Kalpa,Sangla,Theog,Rohru,Bhuntar,Banjar"},
  {
    "name": "Ao",
    "i": 2477,
    "min": 4,
    "max": 12,
    "d": "lnrt",
    "m": 0,
    "b": "Mokokchung,Chuchuyimlang,Changtongya,Ungma,Longkhum,Alongkima,Tuli,Khensa,Longsa,Metsuben,Aliba,Chungtia,Kumlong,Saringyim,Aoizu,Changki,Imsong,Tzudir,Kinunger,Yimyu"},
  {
    "name": "Ole",
    "i": 2489,
    "min": 4,
    "max": 12,
    "d": "lnrt",
    "m": 0,
    "b": "Rukha,Nichula,Lhamoidzingkha,Kalikhola,Sarpangtar,Beteni,Singye,Jigme,Umling,Samtenling,Norbugang,Doban,Panbari,Juruk,Karmaling,GelephuTown,Bhur,Khochu,Chakpikarong,Malbase"},
  {
    "name": "Maori",
    "i": 2587,
    "min": 4,
    "max": 12,
    "d": "lnrt",
    "m": 0,
    "b": "Aotearoa,Tamaki,Manaia,Whangarei,Kaikohe,Kaitaia,Waitangi,Kawhia,Raglan,Turangi,Tokaanu,Taumarunui,Te Kuiti,Te Awamutu,Whakatane,Opotiki,Gisborne,Wairoa,Waipukurau,Otaki,Porirua,Paraparaumu,Wanganui,Whanganui,Ohakune,Featherston,Masterton,Kaikoura,Blenheim"},
  {
    "name": "Samoan",
    "i": 2588,
    "min": 4,
    "max": 12,
    "d": "lnrt",
    "m": 0,
    "b": "Apia,Vaitele,Faleula,Siusega,Afega,Leulumoega,Fasitoouta,Malie,Vailele,Vailima,Saleimoa,Faleasiu,Samatau,Faleolo,Satapuala,Tafuna,Pago Pago,Fagatogo,Utulei,Nu'uuli,Leone,Vailoa,Afono,Vatia,Aua,Laulii,Lalomanu,Safotu,Asau,Satupaitea"},
  {
    "name": "Fijian",
    "i": 2589,
    "min": 4,
    "max": 12,
    "d": "lnrt",
    "m": 0,
    "b": "Suva,Nausori,Nadi,Lautoka,Ba,Tavua,Rakiraki,Labasa,Savusavu,Taveuni,Sigatoka,Navua,Levuka,Seaqaqa,Nabouwalu,Nailaga,Keiyasi,Korolevu,Malolo,Lomawai,Nausori Highlands,Nasinu,Lami,Kinoya,Nakasi,Rewa,Nailaga Village,Cuvu,Naweni,Vatutavui"},
  {
    "name": "Papuan",
    "i": 2671,
    "min": 4,
    "max": 12,
    "d": "lnrt",
    "m": 0,
    "b": "Tari,Mendi,Wabag,Ialibu,Koroba,Kagua,Kundiawa,Kerowagi,Minj,Banz,Goroka,Kainantu,Henganofi,Chuave,Obura,Wapenamanda,Kompiam,Porgera,Enga,Okapa,Menyamya,Finschhafen,Kikori,Tapu,qabiao_20214_u1,qabiao_20214_u2,qabiao_20214_u3,qabiao_20214_u4,qabiao_20214_u5,qabiao_20214_u6,qabiao_20214_u7,qabiao_20214_u8,qabiao_20214_u9,qabiao_20214_u10,qabiao_20214_u11,qabiao_20214_u12"},
  {
    "name": "Nauruan",
    "i": 2685,
    "min": 4,
    "max": 12,
    "d": "lnrt",
    "m": 0,
    "b": "Aiwo,Anabar,Anetan,Anibare,Baiti,Boe,Buada,Denigomodu,Ewa,Ijuw,Meneng,Nibok,Uaboe,Yaren,nau_20215_u1,nau_20215_u2,nau_20215_u3,nau_20215_u4,nau_20215_u5,nau_20215_u6,nau_20215_u7,nau_20215_u8,nau_20215_u9,nau_20215_u10"},
  {
    "name": "Tongan",
    "i": 2744,
    "min": 4,
    "max": 12,
    "d": "lnrt",
    "m": 0,
    "b": "Nuku'alofa,Neiafu,Hihifo,Pangai,Ohonua,Lifuka,Havelu,Vaini,Kolovai,Ha'apai,Vava'u,Eua,Niuatoputapu,Niuafo'ou,Tafahi,Tungua"},
  {
    "name": "Tahitian",
    "i": 2745,
    "min": 4,
    "max": 12,
    "d": "lnrt",
    "m": 0,
    "b": "Papeete,Faaa,Pirae,Mahina,Paea,Papara,Arue,Punaauia,Teiva,Uturoa,Raiatea,Tahaa,Bora Bora,Huahine,Moorea,Tetiaroa,Manihi"},
  {
    "name": "Marshallese",
    "i": 2746,
    "min": 4,
    "max": 12,
    "d": "lnrt",
    "m": 0,
    "b": "Majuro,Ebeye,Ailinglaplap,Jaluit,Wotje,Kwajalein,Enewetak,Ujelang,Bikini,Rongelap,Namoro,Ujae,Ebon,Kili,Mili,Aur,Lae"},
  {
    "name": "Palauan",
    "i": 2747,
    "min": 4,
    "max": 12,
    "d": "lnrt",
    "m": 0,
    "b": "Koror,Airai,Meliikeok,Ngchesar,Ngeremlengui,Ngerchelong,Ngaraard,Peleliu,Angaur,Kayangel,Sonsorol,Hatohobei,Rock Islands,Urukthapel"},
  {
    "name": "Chamorro",
    "i": 2748,
    "min": 4,
    "max": 12,
    "d": "lnrt",
    "m": 0,
    "b": "Hagatna,Dededo,Tamuning,Mongmong-Toto-Maite,Yigo,Agat,Santa Rita,Barrigada,Merizo,Piti,Inarajan,Umatac,Talofofo,Asan-Maina,Agana Heights"},
  {
    "name": "Kiribati",
    "i": 2749,
    "min": 4,
    "max": 12,
    "d": "lnrt",
    "m": 0,
    "b": "Tarawa,Kiritimati,Tabiteuea,Abaiang,Marakei,Maiana,Nikunau,Abemama,Beru,TabiteueaNorth,TabiteueaSouth,Nonouti,Onotoa,Teraina,Kanton,Makin"},
  {
    "name": "Hiri Motu",
    "i": 1888,
    "min": 4,
    "max": 11,
    "d": "nic-GH",
    "m": 0,
    "b": "Hiri,Motu,Police,Papuan,Austronesian,Port Moresby,Sago,Papua New Guinea,Oceania"},
  {
    "name": "Gurindji Kriol",
    "i": 1919,
    "min": 4,
    "max": 11,
    "d": "nic-GH",
    "m": 0,
    "b": "Gurindji,Kriol,Daguragu,Ngukurrwurr,Victoria,Australia,Northern Territory,Kriol Languages"}
  ,
  {
    "name": "Papuan Malay",
    "i": 112,
    "min": 4,
    "max": 11,
    "d": "nic-GH",
    "m": 0,
    "b": "Jayapura,Sorong,Manokwari,Timika,Nabire,Biak,Merauke,Sentani,Wamena,Fakfak,Serui,Kaimana,Wasior,Teminabuan,Kumurkek,Arona,Bintuni,Genyem,Sarmi,Oksibil,Tanah Merah,Agats,Enarotali,Sugapa,Karubaga,Burmeso,Sumohai,Kobakma,Tiom,Kenyam,Elelim,Mulia,Ilaga,Waisai,Ransiki,Anggi,Soug,Maybrat,Ayamaru,Aitinyo,Inanwatan,Kokas,Babo,Teluk Bintuni,Teluk Wondama,Mamberamo,Waropen,Supiori,Yapen,Numfor"},
  {
    "name": "Serui Malay",
    "i": 113,
    "min": 4,
    "max": 11,
    "d": "nic-GH",
    "m": 0,
    "b": "Serui,Yapen,Wondama,Biak,Numfor,Nabire,Waropen,Ransiki,Wasior,Ansus,Jayapura,Sorong,Manokwari,Timika,Fakfak,Merauke,Sentani,Wamena,Kaimana,Teminabuan,Kumurkek,Arona,Bintuni,Genyem,Sarmi,Oksibil,Tanah Merah,Agats,Enarotali,Sugapa,Karubaga,Burmeso,Sumohai,Kobakma,Tiom,Kenyam,Elelim,Mulia,Ilaga,Waisai,Anggi,Maybrat,Ayamaru,Aitinyo,Inanwatan,Kokas,Babo,Menawi,Saubeba,Ambai"},

module.exports = window.oceaniaNameBases;
