const fs = require("fs");
const path = require("path");

const root = "E:/code/Fantasy-Map-Generator";
const jsonPath = path.join(root, "config/language-mixer-map.json");
const jsPath = path.join(root, "config/language-mixer-map.js");

// Read JSON
const jsonContent = fs.readFileSync(jsonPath, "utf8");
const map = JSON.parse(jsonContent);

console.log("JSON entries loaded:", map.length);

// Create JS bundle
const jsContent = `"use strict";

// Auto-generated by tools/generate-language-mixer.js from config/language-mixer-map.json.
// Edit the JSON source and rerun the generator if you change the mapping.
// This map associates language ISO codes with arrays of base language IDs from the namebases.
// Used by the language mixer to determine which base languages to combine for generating names in each language.
(function(){
  globalThis.languageMixerMap = ${JSON.stringify(map, null, 2)};
})();
`;

// Write JS
fs.writeFileSync(jsPath, jsContent, "utf8");

console.log("Wrote JS file:", jsPath);
console.log("First entry:", JSON.stringify(map[0]));