"use strict";

const fs = require("fs");
const path = require("path");

const rootDir = "E:/code/Fantasy-Map-Generator";
const jsonPath = path.join(rootDir, "config/language-mixer-map.json");
const jsPath = path.join(rootDir, "config/language-mixer-map.js");

// Read JSON
const jsonContent = fs.readFileSync(jsonPath, "utf8");
const languageMixerMap = JSON.parse(jsonContent);

// Create JS bundle
const jsContent = [
  '"use strict";',
  "",
  "// Auto-generated by tools/generate-language-mixer.js from config/language-mixer-map.json.",
  "// Edit the JSON source and rerun the generator if you change the mapping.",
  "// This map associates language ISO codes with arrays of base language IDs from the namebases.",
  "// Used by the language mixer to determine which base languages to combine for generating names in each language.",
  "(function(){",
  "  globalThis.languageMixerMap = " + JSON.stringify(languageMixerMap, null, 2) + ";",
  "})();",
  ""
].join("\n");

// Write JS
fs.writeFileSync(jsPath, jsContent, "utf8");

// Report
console.log("DONE - Wrote " + jsPath);
console.log("First entry: " + JSON.stringify(languageMixerMap[0]));
console.log("Total entries: " + languageMixerMap.length);