const fs = require("fs");
const path = require("path");

const root = "E:/code/Fantasy-Map-Generator";

// Read JSON file
const jsonPath = path.join(root, "config/language-mixer-map.json");
const jsonData = fs.readFileSync(jsonPath, "utf8");
const map = JSON.parse(jsonData);

console.log("Read JSON entries:", map.length);
console.log("First entry:", JSON.stringify(map[0]));

// Create JS file content
const banner = [
  '"use strict";',
  "",
  "// Auto-generated by tools/generate-language-mixer.js from config/language-mixer-map.json.",
  "// Edit the JSON source and rerun the generator if you change the mapping.",
  "(function(){",
  "  globalThis.languageMixerMap = " + JSON.stringify(map, null, 2) + ";",
  "})();",
  ""
].join("\n");

const jsPath = path.join(root, "config/language-mixer-map.js");
fs.writeFileSync(jsPath, banner, "utf8");

console.log("Wrote JS file");
console.log("JS first entry:", JSON.stringify(map[0]));