"use strict";
const fs = require("node:fs");
const path = require("node:path");

const dataPath = path.join(__dirname, "../docs/plans/namebase-research/data.json");
if (!fs.existsSync(dataPath)) {
  console.error("ERROR: data file not found: " + dataPath);
  console.error("Run tools/generate-quality-tracker.js first to generate it.");
  process.exit(1);
}
const data = require(dataPath);
const outDir = path.join(__dirname, "../docs/plans/namebase-research");

function langEntry(item) {
  const wiki = item.catalogWiki ? "[" + item.catalogWiki + "](" + item.catalogWiki + ")" : "N/A";
  const lines = [
    "",
    "## " + item.name + " (i:" + item.i + ")",
    "",
    "- Seeds: **" + item.seedCount + "** | Min/Max: **" + item.min + "/" + item.max + "** | m=**" + item.m + "** | d=**" + item.d + "** \u2014 " + wiki,
    "- Sample: " + item.sampleSeeds,
    "- [ ] Name  [ ] Seeds authentic  [ ] Seed count  [ ] D  [ ] M  [ ] Min/Max  [ ] Continent  [ ] Encoding  [ ] Placeholder  [ ] Done",
    ""
  ];
  return lines;
}

const fileGroups = {};
data.forEach(function(item) {
  const f = item.filename;
  if (!fileGroups[f]) fileGroups[f] = [];
  fileGroups[f].push(item);
});

const fileNames = Object.keys(fileGroups).sort();

let totalCombined = 0;

fileNames.forEach(function(fname) {
  const items = fileGroups[fname];
  totalCombined += items.length;

  const fileBase = fname.replace(/\.js$/, "");
  const displayName = fileBase + ".js";

  const header = [
    "# " + displayName + " \u2014 Manual Review (" + items.length + " languages)",
    "",
    "> Every entry is **unverified by default**. An entry becomes valid only when sufficient evidence supports it.",
    "",
    "---",
    ""
  ];

  const body = [];
  items.sort(function(a, b) { return a.i - b.i; });
  items.forEach(function(item) {
    body.push.apply(body, langEntry(item));
  });

  const md = header.concat(body).join("\r\n");
  const outPath = path.join(outDir, fileBase + ".md");
  fs.writeFileSync(outPath, md, "utf8");
  console.log("Wrote " + outPath + " (" + items.length + " languages)");
});

const combinedHeader = [
  "# Namebase Tracker \u2014 Combined Manual Review",
  "",
  "**" + totalCombined + " languages** across **" + fileNames.length + " files**.",
  "",
  "---",
  "",
  "## Purpose",
  "",
  "This tracker provides a manageable, per-entry checklist for manually reviewing",
  "every language namebase entry. Each entry must be validated across multiple dimensions.",
  "",
  "## Review Dimensions",
  "",
  "- **Name** \u2014 Language name is accurate and properly spelled  ",
  "- **Seeds authentic** \u2014 Sample seeds come from real placenames in that language  ",
  "- **Seed count** \u2014 Number of seeds is sufficient for the mixer  ",
  "- **D** \u2014 Distribution codes (d) match the language's phonotactics  ",
  "- **M** \u2014 Mutation rate (m) is appropriate  ",
  "- **Min/Max** \u2014 Name length range is reasonable  ",
  "- **Continent** \u2014 Geographic assignment is correct  ",
  "- **Encoding** \u2014 Any special characters render correctly  ",
  "- **Placeholder** \u2014 Mark if entry is a stub needing replacement  ",
  "- **Done** \u2014 Fully reviewed and approved  ",
  "",
  "---",
  ""
];

const combinedBody = [];
fileNames.forEach(function(fname) {
  const items = fileGroups[fname];
  const displayName = fname;
  combinedBody.push("");
  combinedBody.push("## " + displayName + " (" + items.length + " languages)");
  combinedBody.push("");
  items.sort(function(a, b) { return a.i - b.i; });
  items.forEach(function(item) {
    combinedBody.push.apply(combinedBody, langEntry(item));
  });
});

const guidelines = [
  "---",
  "",
  "## Research Guidelines",
  "",
  "### How to Review a Language Entry",
  "",
  "1. **Search Wikipedia** for the language name to confirm it exists  ",
  "2. **Verify seeds** \u2014 Search for sample seeds as real placenames  ",
  "3. **Check D values** \u2014 Ensure distribution codes fit the language  ",
  "     - l = liquids, n = nasals, r = rhotics, s = sibilants, etc.  ",
  "4. **Check M value** \u2014 Mutation rate (0-1) should reflect variability  ",
  "5. **Check Min/Max** \u2014 Reasonable name lengths (typically 3-15)  ",
  "6. **Flag placeholders** \u2014 Mark entries needing replacement or expansion  ",
  "",
  "### Priority Order",
  "",
  "1. Check for placeholder or garbage data  ",
  "2. Verify language name against Wikipedia  ",
  "3. Spot-check first 3-5 seeds for authenticity  ",
  "4. Verify numeric vs alphabetic seed ratio is balanced  ",
  "",
  "### Tools",
  "",
  "- Wikipedia search: https://en.wikipedia.org/wiki/[Language]_language  ",
  "- GeoNames: https://www.geonames.org/  ",
  "- Glottolog: https://glottolog.org/  ",
  "",
  "---",
  "",
  "*Generated by tools/generate-tracker.js*  ",
  "*Total: " + totalCombined + " languages across " + fileNames.length + " files*  "
];

const combinedMd = combinedHeader.concat(combinedBody).concat(guidelines).join("\r\n");
const combinedPath = path.join(outDir, "TRACKER.md");
fs.writeFileSync(combinedPath, combinedMd, "utf8");
console.log("Wrote " + combinedPath + " (" + totalCombined + " total languages)");
